# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: error
  logs:
    custom_components.kocom_wallpad: debug
